server:
  http_port: "8010"
  grpc:
    auth:
      port: "9005"
      host: "localhost"
  env: "development"

database:
  host: "host.docker.internal"
  port: "5432"
  user: "postgres"
  password: "postgres"
  name: "product_service"
  sslmode: "disable"
  max_idle_conns : 10
  max_open_conns : 100

redis:
  addr: "host.docker.internal:6379"
  pass: "redis_password"
  db: 0


logging:
  level: "info"